<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="admin-PC" ignored="0" name="Add customer" tests="3" failures="1" timestamp="2019-10-18T07:15:24 EEST" time="9.035" errors="0">
  <testcase name="addCustomerTest" time="1.258" classname="bankManager.testcases.AddCustomerTest"/>
  <testcase name="addCustomerTest" time="0.329" classname="bankManager.testcases.AddCustomerTest"/>
  <testcase name="addCustomerTest" time="0.335" classname="bankManager.testcases.AddCustomerTest">
    <failure type="java.lang.AssertionError" message="java.lang.AssertionError: 
Expected: a string containing &amp;quot;Aaaaaaaaaa&amp;quot;
     but: was &amp;quot;Customer added successfully with customer id :8&amp;quot;">
      <![CDATA[java.lang.AssertionError: java.lang.AssertionError: 
Expected: a string containing "Aaaaaaaaaa"
     but: was "Customer added successfully with customer id :8"
at bankManager.testcases.AddCustomerTest.addCustomerTest(AddCustomerTest.java:51)
at java.util.ArrayList.forEach(Unknown Source)
Caused by: java.lang.AssertionError: 
Expected: a string containing "Aaaaaaaaaa"
     but: was "Customer added successfully with customer id :8"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
at bankManager.testcases.AddCustomerTest.addCustomerTest(AddCustomerTest.java:45)
... 28 more
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- addCustomerTest -->
</testsuite> <!-- Add customer -->
