<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="3" failed="0" ignored="0" total="3" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Data driven Framework" duration-ms="10347" started-at="2019-10-30T03:21:42 EET" finished-at="2019-10-30T03:21:52 EET">
    <groups>
    </groups>
    <test name="Test" duration-ms="10347" started-at="2019-10-30T03:21:42 EET" finished-at="2019-10-30T03:21:52 EET">
      <class name="bankManager.testcases.AddCustomerTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:bankManager.testcases.AddCustomerTest@48524010]" name="setUp" is-config="true" duration-ms="6520" started-at="2019-10-30T03:21:42 EET" finished-at="2019-10-30T03:21:49 EET">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="SKIP" signature="addCustomerTest(java.util.Hashtable)[pri:0, instance:bankManager.testcases.AddCustomerTest@48524010]" name="addCustomerTest" duration-ms="83" started-at="2019-10-30T03:21:50 EET" data-provider="bankManagerDP" finished-at="2019-10-30T03:21:50 EET">
          <params>
            <param index="0">
              <value>
                <![CDATA[{PostCode=A4454578, RunMode=Y, FirstName=Salman, Alert=Customer added successfully, LastName=Sattar}]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Skipping the test addCustomerTest]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Skipping the test addCustomerTest
at utilities.DataUtil.checkExecutionSuite(DataUtil.java:76)
at bankManager.testcases.AddCustomerTest.addCustomerTest(AddCustomerTest.java:27)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addCustomerTest -->
        <test-method status="PASS" signature="settingup()[pri:0, instance:bankManager.testcases.AddCustomerTest@48524010]" name="settingup" is-config="true" duration-ms="410" started-at="2019-10-30T03:21:50 EET" finished-at="2019-10-30T03:21:50 EET">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- settingup -->
        <test-method status="SKIP" signature="addCustomerTest(java.util.Hashtable)[pri:0, instance:bankManager.testcases.AddCustomerTest@48524010]" name="addCustomerTest" duration-ms="67" started-at="2019-10-30T03:21:50 EET" data-provider="bankManagerDP" finished-at="2019-10-30T03:21:51 EET">
          <params>
            <param index="0">
              <value>
                <![CDATA[{PostCode=A5454545, RunMode=Y, FirstName=lalu, Alert=Customer added successfully, LastName=lattar}]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Skipping the test addCustomerTest]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Skipping the test addCustomerTest
at utilities.DataUtil.checkExecutionSuite(DataUtil.java:76)
at bankManager.testcases.AddCustomerTest.addCustomerTest(AddCustomerTest.java:27)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addCustomerTest -->
        <test-method status="PASS" signature="settingup()[pri:0, instance:bankManager.testcases.AddCustomerTest@48524010]" name="settingup" is-config="true" duration-ms="228" started-at="2019-10-30T03:21:51 EET" finished-at="2019-10-30T03:21:51 EET">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- settingup -->
        <test-method status="SKIP" signature="addCustomerTest(java.util.Hashtable)[pri:0, instance:bankManager.testcases.AddCustomerTest@48524010]" name="addCustomerTest" duration-ms="85" started-at="2019-10-30T03:21:51 EET" data-provider="bankManagerDP" finished-at="2019-10-30T03:21:51 EET">
          <params>
            <param index="0">
              <value>
                <![CDATA[{PostCode=B4545, RunMode=Y, FirstName=kalu, Alert=Aaaaaaaaaa, LastName=kattar}]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Skipping the test addCustomerTest]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Skipping the test addCustomerTest
at utilities.DataUtil.checkExecutionSuite(DataUtil.java:76)
at bankManager.testcases.AddCustomerTest.addCustomerTest(AddCustomerTest.java:27)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addCustomerTest -->
        <test-method status="PASS" signature="settingup()[pri:0, instance:bankManager.testcases.AddCustomerTest@48524010]" name="settingup" is-config="true" duration-ms="233" started-at="2019-10-30T03:21:51 EET" finished-at="2019-10-30T03:21:51 EET">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- settingup -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:bankManager.testcases.AddCustomerTest@48524010]" name="tearDown" is-config="true" duration-ms="1273" started-at="2019-10-30T03:21:51 EET" finished-at="2019-10-30T03:21:52 EET">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- bankManager.testcases.AddCustomerTest -->
    </test> <!-- Test -->
  </suite> <!-- Data driven Framework -->
</testng-results>
